version: '2'

services:
    app:
        build:
            context: ./
            dockerfile: ./docker/app/Dockerfile
        volumes:
            - /app
        depends_on:
            - db
        links:
            - db:db
        networks:
            - default
        ports:
            - "8080:8080"
        
    db:
        image: postgres:9.3.20
        restart: always
        environment:
            POSTGRES_USER: fms
            POSTGRES_PASSWORD: fms
            POSTGRES_DB: fms
        ports:
            - "5432:5432"
        expose:
            - "5432"

networks:
    default:
        driver: "bridge"